apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: client
  template:
    metadata:
      labels:
        component: client
    spec:
      containers:
        - name: client
          image: $CLIENT_IMAGE
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: client-secrets
                  key: REACT_APP_SERVER_URL
            - name: REACT_APP_STRIPE_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: client-secrets
                  key: REACT_APP_STRIPE_PUBLISHABLE_KEY
            - name: REACT_APP_STRIPE_REGISTRATION_PRICE_ID
              valueFrom:
                secretKeyRef:
                  name: client-secrets
                  key: REACT_APP_STRIPE_REGISTRATION_PRICE_ID
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    component: client
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer