apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
type: Opaque
data:
  REACT_APP_SERVER_URL: $REACT_APP_SERVER_URL
  REACT_APP_STRIPE_PUBLISHABLE_KEY: $REACT_APP_STRIPE_PUBLISHABLE_KEY
  REACT_APP_STRIPE_REGISTRATION_PRICE_ID: $REACT_APP_STRIPE_REGISTRATION_PRICE_ID
