apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: $SERVER_IMAGE
          ports:
            - containerPort: 3000
          env:
          - name: DATABASE_URL
            value: $DATABASE_URL

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    component: server
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer