FROM postgres:15.0.0-alpine as database_builder

ARG POSTGRES_PASSWORD
ARG POSTGRES_USER
ARG POSTGRES_DB

ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_DB=${POSTGRES_DB}

FROM node:18.0.0-alpine as node_builder

ARG DATABASE_URL
ENV DATABASE_URL $DATABASE_URL

WORKDIR /home/athlete-registration-system/server

RUN npm install prisma@5.7.1

COPY server/prisma ./prisma
COPY server/package.json server/package-lock.json ./

CMD npx prisma migrate deploy
