apiVersion: apps/v1
kind: Deployment
metadata:
  name: athelete-registration-system-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: athelete-registration-system-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: athelete-registration-system-server
    spec:
      containers:
        - name: backend
          image: $CLIENT_IMAGE
          ports:
            - name: http
              containerPort: 3000
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 300m
              memory: 200Mi