name: BUILD

on:
  pull_request:
    branches: [ "develop", "master", "hotfix/**", "feature/**", "bugfix/**", "release/**"]

  workflow_dispatch:

env:
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/mindmap_test?schema=public
  APP_PORT: 3000


jobs:
  build_server:
    name: Build Server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: cd server && npm ci
      - name: Lint
        run: cd server && npm run lint
      - name: Build
        run: cd server && npm run build --if-present

  
  build_client:
    name: Build Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: cd client && npm ci
      - name: Build
        run: cd client && npm run build --if-present 