name: RELEASE

on:
  push:
    branches:
      - master
    
jobs:
    build-client:
        runs-on: ubuntu-latest
        permissions:
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: set lower case owner name
              run: |
                    echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
              env:
                    OWNER: '${{ github.actor }}'
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./client/Dockerfile
                push: true
                tags: ghcr.io/${{ env.OWNER_LC }}/sebizclient:${{ github.run_id }}

    build-server:
        runs-on: ubuntu-latest
        permissions:
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: set lower case owner name
              run: |
                    echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
              env:
                    OWNER: '${{ github.actor }}'
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./server/Dockerfile
                push: true
                tags: ghcr.io/${{ env.OWNER_LC }}/sebizserver:${{ github.run_id }}

    build-database:
        runs-on: ubuntu-latest
        needs: [build-server]
        permissions:
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: set lower case owner name
              run: |
                    echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
              env:
                    OWNER: '${{ github.actor }}'
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./server/Dockerfile.migrations
                push: true
                tags: ghcr.io/${{ env.OWNER_LC }}/sebizdatabase:${{ github.run_id }}   

    deploy-client-kube:
        name: Deploy client to Kubernetes
        needs: [build-client]
        runs-on: ubuntu-latest
        permissions:
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
  
            - name: Set up doctl
              uses: digitalocean/action-doctl@v2
              with:
                token: ${{ secrets.DIGITAL_OCEAN_API_TOKEN_KEY }}

            - name: Set up kubectl
              uses: tale/kubectl-action@v1
              with:
                base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: set lower case owner name
              run: |
                    echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
              env:
                    OWNER: '${{ github.actor }}'

            - name: Deploy to Kubernetes
              run:
                |
                export CLIENT_IMAGE=ghcr.io/${{ env.OWNER_LC }}/sebizclient:${{ github.run_id }}
                cat manifests/client-deployment.yml | envsubst | kubectl apply -f -

    deploy-server-kube:
        name: Deploy server to Kubernetes
        needs: [build-database]
        runs-on: ubuntu-latest
        permissions:
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
  
            - name: Set up doctl
              uses: digitalocean/action-doctl@v2
              with:
                token: ${{ secrets.DIGITAL_OCEAN_API_TOKEN_KEY }}

            - name: Set up kubectl
              uses: tale/kubectl-action@v1
              with:
                base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: set lower case owner name
              run: |
                    echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
              env:
                    OWNER: '${{ github.actor }}'

            - name: Deploy to Kubernetes
              run:
                |
                export SERVER_IMAGE=ghcr.io/${{ env.OWNER_LC }}/sebizserver:${{ github.run_id }}
                cat manifests/server-deployment.yml | envsubst | kubectl apply -f -
                export DATABASE_IMAGE=ghcr.io/${{ env.OWNER_LC }}/sebizdatabase:${{ github.run_id }}
                cat manifests/postgres-deployment.yml | envsubst | kubectl apply -f -